# Generated by Django 3.2 on 2021-04-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(default=None, null=True)),
                ('gender', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], default=None, max_length=1, null=True)),
                ('hobbies', models.PositiveIntegerField(default=None, null=True)),
                ('is_updated', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.cluster')),
                ('occupation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.occupation')),
            ],
        ),
    ]
