# Generated by Django 3.2 on 2021-04-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female'), ('2', 'Others')], default=None, max_length=1, null=True),
        ),
    ]
