# Generated by Django 3.2 on 2021-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20210410_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
