# Generated by Django 3.2 on 2021-04-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_profile_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
