# Generated by Django 3.2 on 2021-04-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0011_alter_profile_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
