# Generated by Django 3.2 on 2021-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
