# Generated by Django 3.2 on 2021-04-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_is_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_updated',
        ),
    ]
