# Generated by Django 3.2 on 2021-04-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measure_app', '0001_initial'),
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.activity'),
        ),
        migrations.AddField(
            model_name='priority',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_app.cluster'),
        ),
    ]
